add basic UI
BANCUNGUYE66/school_library pull request #4
Opened 2023-06-22 15:03 UTC by BANCUNGUYE66

### OOP school library: add basic UI

- Build interactive console apps.
- Run a program using the command line.

2023-06-22 15:15 UTC, frank1738 requested changes
Hi @BANCUNGUYE66 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>


## Highlights

✅ Correct use of Gitflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 15:15 UTC, ghost commented on app.rb
> +    case choice
- [ ] Kindly check out this [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) to implement the correct flow on how the app should run. For instance, when creating a person,  the first field to be filled is either `you are a student or a teacher?`

2023-06-23 01:43 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @BANCUNGUYE66 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 01:43 UTC, tresorsawasawa commented on app.rb
> +
- [ ] Good job trying to implement all the changes mentioned by the previous reviewer. However, I noticed that there is error that occurs when user want to exit to your application by clicking the option `'7. Quit'`. Your application is supposed to behave in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) that was provided for you. This is the major requirement of the project. Below is the error I get, make sure you fix it:
![image](https://github.com/BANCUNGUYE66/school_library/assets/83042742/78a6c1fc-947e-409d-9079-fa6b66312c41)

2023-06-23 11:42 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- You have successfully completed the changes requested by the previous code reviewer. ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 13:36 UTC, merged